# Generated by Django 2.2.10 on 2020-02-09 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='meeting',
            name='title',
            field=models.CharField(default='Meeting', max_length=100),
        ),
    ]
