# Generated by Django 2.2.10 on 2020-02-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20200208_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='John Doe', max_length=100),
        ),
    ]
