# Generated by Django 2.2.10 on 2020-02-09 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_auto_20200208_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='John Doe', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='meeting',
            name='users',
            field=models.ManyToManyField(to='scheduler.User'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='scheduler.User'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduler.User'),
        ),
    ]
